/** Stored in `analytics_events.event` (CHECK constraint derives from these values, Spec §23.3). */
export enum AnalyticsEvent {
  UPLOAD_STARTED = 'upload_started',
  RECOGNITION_COMPLETED = 'recognition_completed',
  LOGIN_COMPLETED = 'login_completed',
  JOB_CLAIMED = 'job_claimed',
  DRAFT_CREATED = 'draft_created',
  REVIEW_COMPLETED = 'review_completed',
  MONTH_PUBLISHED = 'month_published',
  NEXT_MONTH_REGISTERED = 'next_month_registered',
  CALENDAR_VIEWED = 'calendar_viewed',
  EXPORT_LINK = 'export_link',
  SHARED_CALENDAR_VIEWED = 'shared_calendar_viewed',
  EXPORT_ICS = 'export_ics',
  EXPORT_PNG = 'export_png',
  TEAM_CREATED = 'team_created',
  ROSTER_PUBLISHED = 'roster_published',
  TEAM_MEMBER_JOINED = 'team_member_joined',
  PAYMENT_SHOWN = 'payment_shown',
  PAYMENT_SUCCEEDED = 'payment_succeeded',
  // Entry screen and sample trial (Spec §26.5). Client events arrive through POST /api/events.
  LANDING_UPLOAD_CLICKED = 'landing_upload_clicked',
  SAMPLE_STARTED = 'sample_started',
  SAMPLE_COMPLETED = 'sample_completed',
  SAMPLE_CTA_CLICKED = 'sample_cta_clicked',
  SHARE_LATER_CLICKED = 'share_later_clicked',
  LOGIN_CLICKED = 'login_clicked',
  /** Recorded by the OAuth callback (server), never accepted from the client. */
  LOGIN_FAILED = 'login_failed',
}
